# Generated by Django 5.0.7 on 2024-07-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_str', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('protected', models.BooleanField(default=False)),
                ('followers_count', models.IntegerField(default=0)),
                ('friends_count', models.IntegerField(default=0)),
                ('listed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('favourites_count', models.IntegerField(default=0)),
                ('utc_offset', models.IntegerField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('geo_enabled', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('statuses_count', models.IntegerField(default=0)),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
                ('contributors_enabled', models.BooleanField(default=False)),
                ('is_translator', models.BooleanField(default=False)),
                ('is_translation_enabled', models.BooleanField(default=False)),
                ('profile_background_color', models.CharField(blank=True, max_length=6, null=True)),
                ('profile_background_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('profile_background_image_url_https', models.URLField(blank=True, max_length=500, null=True)),
                ('profile_background_tile', models.BooleanField(default=False)),
                ('profile_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('profile_image_url_https', models.URLField(blank=True, max_length=500, null=True)),
                ('profile_banner_url', models.URLField(blank=True, max_length=500, null=True)),
                ('profile_link_color', models.CharField(blank=True, max_length=6, null=True)),
                ('profile_sidebar_border_color', models.CharField(blank=True, max_length=6, null=True)),
                ('profile_sidebar_fill_color', models.CharField(blank=True, max_length=6, null=True)),
                ('profile_text_color', models.CharField(blank=True, max_length=6, null=True)),
                ('profile_use_background_image', models.BooleanField(default=False)),
                ('default_profile', models.BooleanField(default=False)),
                ('default_profile_image', models.BooleanField(default=False)),
                ('following', models.BooleanField(blank=True, null=True)),
                ('follow_request_sent', models.BooleanField(blank=True, null=True)),
                ('notifications', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(unique=True)),
                ('id_str', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('truncated', models.BooleanField(default=False)),
                ('in_reply_to_status_id', models.BigIntegerField(blank=True, null=True)),
                ('in_reply_to_status_id_str', models.CharField(blank=True, max_length=20, null=True)),
                ('in_reply_to_user_id', models.BigIntegerField(blank=True, null=True)),
                ('in_reply_to_user_id_str', models.CharField(blank=True, max_length=20, null=True)),
                ('in_reply_to_screen_name', models.CharField(blank=True, max_length=255, null=True)),
                ('geo', models.JSONField(blank=True, null=True)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('contributors', models.JSONField(blank=True, null=True)),
                ('retweet_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('favorited', models.BooleanField(default=False)),
                ('retweeted', models.BooleanField(default=False)),
                ('possibly_sensitive', models.BooleanField(blank=True, null=True)),
                ('filter_level', models.CharField(blank=True, max_length=50, null=True)),
                ('lang', models.CharField(max_length=10)),
                ('retweeted_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='api.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('indices', models.JSONField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='api.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('indices', models.JSONField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='api.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('expanded_url', models.URLField(max_length=500)),
                ('display_url', models.CharField(max_length=255)),
                ('indices', models.JSONField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='api.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='UserMention',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('screen_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('id_str', models.CharField(max_length=20)),
                ('indices', models.JSONField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='api.tweet')),
            ],
        ),
    ]
