# Generated by Django 5.0.7 on 2024-07-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='usermention',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelTable(
            name='hashtag',
            table='tb_tweet_hashtags',
        ),
        migrations.AlterModelTable(
            name='symbol',
            table='tb_tweet_symbols',
        ),
        migrations.AlterModelTable(
            name='tweet',
            table='tb_tweets',
        ),
        migrations.AlterModelTable(
            name='url',
            table='tb_tweet_url',
        ),
        migrations.AlterModelTable(
            name='user',
            table='tb_tweet_users',
        ),
        migrations.AlterModelTable(
            name='usermention',
            table='tb_tweet_user_mentions',
        ),
    ]
